# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# before:
#   hooks:
#     # you may remove this if you don't use vgo
#     - go mod download
#     # you may remove this if you don't need go generate
#     - go generate ./...
builds:
- goos:
  - windows
- goarch:
  - arm
  - arm64
- env:
  - CGO_ENABLED=0
dockers:
  - 
    dockerfile: "build/gorDockerfile"
    binaries:
    - google-domains-ddns-updater
    image_templates:
    - "stevenweathers/google-domains-ddns-updater:{{ .Tag }}"
    - "stevenweathers/google-domains-ddns-updater:latest"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
    arm: arm
    arm64: arm_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dist: release